kGetOrCreateTag: 0
kGetTagId: 1
kGetTagName: 2
kRenameTag: 3
kDestroyTag: 4
kTagAddBlob: 5
kTagRemoveBlob: 6
kTagGroupBy: 7
kTagAddTrait: 8
kTagRemoveTrait: 9
kTagClearBlobs: 10
kPutBlob: 11
kGetBlob: 12
kTruncateBlob: 13
kDestroyBlob: 14
kTagBlob: 15
kUntagBlob: 16
kBlobHasTag: 17
kGetBlobTags: 18
kGetBlobId: 19
kGetBlobName: 20
kGetBlobSize: 21
kGetBlobScore: 22
kGetBlobBuffers: 23
kRenameBlob: 24