execution_method: async
mount_point: "fs::/home/luke"
dag:
  - labmod_uuid: "fs::/home/luke"
    labmod: "LabFS"
    next: "iosched::NoOp"
    do_format: true
    device: "/dev/sda1"
  - labmod_uuid: "iosched::NoOp"
    labmod: "NoOp"
    next: "driver::MQDriver"
  - labmod_uuid: "driver::MQDriver"
    labmod: "KernDriver"
    device: "/dev/sda1"
