//
// Created by lukemartinlogan on 11/18/21.
//

#ifndef LABSTOR_RUNTIME_MACROS_H
#define LABSTOR_RUNTIME_MACROS_H

#include <labstor/constants/macros.h>
#include <labstor/util/singleton.h>
#define LABSTOR_CONFIGURATION_MANAGER_CLASS labstor::Runtime::ConfigurationManager
#define LABSTOR_IPC_MANAGER_CLASS labstor::Runtime::IPCManager
#define LABSTOR_MODULE_MANAGER_CLASS labstor::Runtime::ModuleManager
#define LABSTOR_WORK_ORCHESTRATOR_CLASS labstor::Runtime::WorkOrchestrator
#define LABSTOR_NAMESPACE_CLASS labstor::Runtime::Namespace
#define LABSTOR_REGISTRAR_CLASS labstor::Registrar::Runtime

#define LABSTOR_CONFIGURATION_MANAGER_T SINGLETON_T(LABSTOR_CONFIGURATION_MANAGER_CLASS)
#define LABSTOR_IPC_MANAGER_T SINGLETON_T(LABSTOR_IPC_MANAGER_CLASS)
#define LABSTOR_MODULE_MANAGER_T SINGLETON_T(LABSTOR_MODULE_MANAGER_CLASS)
#define LABSTOR_WORK_ORCHESTRATOR_T SINGLETON_T(LABSTOR_WORK_ORCHESTRATOR_CLASS)
#define LABSTOR_NAMESPACE_T SINGLETON_T(LABSTOR_NAMESPACE_CLASS)
#define LABSTOR_REGISTRAR_T SINGLETON_T(LABSTOR_REGISTRAR_CLASS)

#define LABSTOR_CONFIGURATION_MANAGER_SINGLETON scs::Singleton<LABSTOR_CONFIGURATION_MANAGER_CLASS>
#define LABSTOR_IPC_MANAGER_SINGLETON scs::Singleton<LABSTOR_IPC_MANAGER_CLASS>
#define LABSTOR_MODULE_MANAGER_SINGLETON scs::Singleton<LABSTOR_MODULE_MANAGER_CLASS>
#define LABSTOR_WORK_ORCHESTRATOR_SINGLETON scs::Singleton<LABSTOR_WORK_ORCHESTRATOR_CLASS>
#define LABSTOR_NAMESPACE_SINGLETON scs::Singleton<LABSTOR_NAMESPACE_CLASS>
#define LABSTOR_REGISTRAR_SINGLETON scs::Singleton<LABSTOR_REGISTRAR_CLASS>

#define LABSTOR_CONFIGURATION_MANAGER scs::Singleton<LABSTOR_CONFIGURATION_MANAGER_CLASS>::GetInstance()
#define LABSTOR_IPC_MANAGER scs::Singleton<LABSTOR_IPC_MANAGER_CLASS>::GetInstance()
#define LABSTOR_MODULE_MANAGER scs::Singleton<LABSTOR_MODULE_MANAGER_CLASS>::GetInstance()
#define LABSTOR_WORK_ORCHESTRATOR scs::Singleton<LABSTOR_WORK_ORCHESTRATOR_CLASS>::GetInstance()
#define LABSTOR_NAMESPACE scs::Singleton<LABSTOR_NAMESPACE_CLASS>::GetInstance()
#define LABSTOR_REGISTRAR scs::Singleton<LABSTOR_REGISTRAR_CLASS>

#endif //LABSTOR_RUNTIME_MACROS_H
